import type { Metadata } from "next";
import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { StoreProvider } from "@/store/storeProvider";
import { useDispatch } from "react-redux";
import { createClient } from "./utils/supabase/server";

const noto = Noto_Kufi_Arabic({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user;
  const supabase = createClient();
  const { data, error } = await supabase.auth.getUser();
  if (data && !error) {
    user = data.user?.role;
  } else {
    user = null;
  }
  return (
    <StoreProvider>
      <html>
        <body className={`${noto.className} md:mt-[5rem]`}>
          <Navbar auth={user ? user : null} />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
